import html2canvas from 'html2canvas-pro';
import { jsPDF } from 'jspdf';

interface PDFMeta {
  employeeId?: string;
  employeeName?: string;
  generatedBy: string;
  title: string;
}

export async function generateA4PDF(
  pages: HTMLElement[],
  filename: string,
  meta: PDFMeta
): Promise<boolean> {
  const opts = {
    scale: 2.0, // High-resolution crisp export
    useCORS: true,
    allowTaint: false,
    backgroundColor: '#ffffff',
    logging: false,
    scrollX: 0,
    scrollY: 0
  };

  try {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const totalPages = pages.length;

    for (let i = 0; i < totalPages; i++) {
      const pageElement = pages[i];
      
      // Render canvas of the page element
      const canvas = await html2canvas(pageElement, opts);
      const imgData = canvas.toDataURL('image/jpeg', 0.95);

      if (i > 0) {
        pdf.addPage();
      }

      // Standard A4 sizes
      const a4Width = 210; // mm
      const a4Height = 297; // mm
      
      const margin = 10; // 10mm margins
      const contentWidth = a4Width - (margin * 2);
      const contentHeight = a4Height - (margin * 2) - 15; // leaves space for repeating header/footer

      const aspect = canvas.height / canvas.width;
      const destHeight = Math.min(contentHeight, contentWidth * aspect);

      // Render Page Content image in center
      const yOffset = margin + 10; // Start below repeating header
      pdf.addImage(imgData, 'JPEG', margin, yOffset, contentWidth, destHeight);

      // --- 1. RENDER ENTERPRISE HEADER ---
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(8);
      pdf.setTextColor(100, 116, 139); // Slate-500
      pdf.text(meta.title, margin, margin);
      
      // Generation Timestamp
      const dateStr = new Date().toLocaleString();
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(7);
      pdf.text(`Export Date: ${dateStr}`, a4Width - margin, margin, { align: 'right' });
      
      // Border line under header
      pdf.setDrawColor(226, 232, 240); // Slate-200
      pdf.setLineWidth(0.3);
      pdf.line(margin, margin + 2, a4Width - margin, margin + 2);

      // --- 2. RENDER ENTERPRISE FOOTER ---
      const footerY = a4Height - margin;
      pdf.line(margin, footerY - 5, a4Width - margin, footerY - 5);

      pdf.setFontSize(7);
      pdf.setTextColor(148, 163, 184); // Slate-400
      pdf.text(`Generated By: ${meta.generatedBy}`, margin, footerY);
      
      // Verification Code / Future-ready QR code indicator
      const verifyCode = meta.employeeId ? `VERIFY-ID: ${meta.employeeId}-${Date.now().toString().slice(-4)}` : 'VERIFY: OFFICIAL';
      pdf.text(verifyCode, a4Width / 2, footerY, { align: 'center' });

      // Page numbers (Page X of Y)
      pdf.text(`Page ${i + 1} of ${totalPages}`, a4Width - margin, footerY, { align: 'right' });

      // Future-ready QR code placeholder drawing (Draw a small square with outline in the footer area)
      const qrSize = 6;
      const qrX = a4Width - margin - 25;
      const qrY = footerY - 4.5;
      pdf.setDrawColor(100, 116, 139);
      pdf.rect(qrX, qrY, qrSize, qrSize);
      pdf.setFontSize(5);
      pdf.text('QR VERIFY', qrX + 0.5, qrY + 3.5);
    }

    pdf.save(filename);
    return true;
  } catch (error) {
    console.error('Unified generateA4PDF Failed:', error);
    alert('Unified PDF rendering error: ' + error);
    return false;
  }
}
